import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./_components/NavBar";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main className="mt-12 px-20 max-xl:px-8 max-md:px-6">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
