import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./_components/NavBar";
import Footer from "./_components/Footer";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* This is do avoid layout shifts or hydration errors with theme toggling */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                const theme = localStorage.getItem('theme') || 
                  (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
                document.documentElement.classList.toggle('dark', theme === 'dark');
              } catch {}
            `,
          }}
        />
      </head>
      <body>
        <NavBar />
        <main className="mt-12 px-20 max-xl:px-8 max-md:px-6">{children}</main>
        <Footer />

        <Toaster
          position="top-center"
          reverseOrder={false}
          gutter={8}
          toastOptions={{
            // Default options for all toasts
            duration: 4000,
            style: {
              background: "#fff",
              color: "#363636",
              padding: "16px 20px",
              borderRadius: "12px",
              fontSize: "15px",
              fontWeight: "500",
              boxShadow:
                "0 10px 25px rgba(0, 0, 0, 0.15), 0 4px 10px rgba(0, 0, 0, 0.1)",
              maxWidth: "420px",
              border: "1px solid rgba(0, 0, 0, 0.05)",
            },

            // Success toast styles
            success: {
              duration: 4000,
              style: {
                background: "linear-gradient(135deg, #10b981 0%, #059669 100%)",
                color: "#ffffff",
                padding: "18px 24px",
                borderRadius: "12px",
                fontSize: "15px",
                fontWeight: "500",
                boxShadow:
                  "0 10px 25px rgba(16, 185, 129, 0.3), 0 4px 10px rgba(16, 185, 129, 0.2)",
                border: "1px solid rgba(255, 255, 255, 0.1)",
              },
              iconTheme: {
                primary: "#ffffff",
                secondary: "#10b981",
              },
            },

            // Error toast styles
            error: {
              duration: 5000,
              style: {
                background: "linear-gradient(135deg, #ef4444 0%, #dc2626 100%)",
                color: "#ffffff",
                padding: "18px 24px",
                borderRadius: "12px",
                fontSize: "15px",
                fontWeight: "500",
                boxShadow:
                  "0 10px 25px rgba(239, 68, 68, 0.3), 0 4px 10px rgba(239, 68, 68, 0.2)",
                border: "1px solid rgba(255, 255, 255, 0.1)",
              },
              iconTheme: {
                primary: "#ffffff",
                secondary: "#ef4444",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
